# Generated by Django 4.1.3 on 2022-11-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_lostimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('documents', 'Документ'), ('keys', 'Ключи'), ('technique', 'Техника'), ('wallets', 'Кошельки'), ('amimals', 'Животные'), ('decorations', 'Украшения'), ('bags', 'Сумки'), ('other', 'Другое')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='lost',
            name='category',
        ),
        migrations.AddField(
            model_name='lost',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='publications', to='post.category'),
        ),
    ]
