# Generated by Django 4.1.3 on 2022-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_category_remove_lost_category_lost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=35, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, choices=[('documents', 'Документ'), ('keys', 'Ключи'), ('technique', 'Техника'), ('wallets', 'Кошельки'), ('amimals', 'Животные'), ('decorations', 'Украшения'), ('bags', 'Сумки'), ('other', 'Другое')], max_length=100),
        ),
    ]
