# Generated by Django 4.1.3 on 2022-11-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_lost_category_delete_category_lost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='category',
            field=models.CharField(choices=[('documents', 'Документ'), ('keys', 'Ключи'), ('technique', 'Техника'), ('wallets', 'Кошельки'), ('animals', 'Животные'), ('decorations', 'Украшения'), ('bags', 'Сумки'), ('other', 'Другое')], default=False, max_length=100),
        ),
    ]
