# Generated by Django 4.1.3 on 2022-11-06 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Find',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Что вы нашли?')),
                ('slug', models.SlugField(blank=True, max_length=170, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='find_images')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='draft', max_length=15)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('documents', 'Документ'), ('keys', 'Ключи'), ('technique', 'Техника'), ('wallets', 'Кошельки'), ('animals', 'Животные'), ('decorations', 'Украшения'), ('bags', 'Сумки'), ('other', 'Другое')], max_length=100)),
                ('address', models.CharField(choices=[('XXXXXX', 'xxxxxx'), ('YYYYYY', 'yyyyyy')], max_length=100)),
                ('date', models.DateField(verbose_name='Дата находки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
